name: mkag
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
<<<<<<< HEAD
  http: ^1.2.2
  rename_app: ^1.6.1
=======
  rename_app: ^1.6.1
  speech_to_text: ^6.6.1
  flutter_tts: ^4.0.2

>>>>>>> voice_document

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/atwlogo.png
    - assets/micicon.svg
    - assets/background.jpg
    

    
